#!/bin/bash


sudo yum install -y \redhat-lsb-core \wget \rpmdevtools \rpm-build \createrepo \yum-utils

cd /home/vagrant/
sudo wget https://nginx.org/packages/centos/7/SRPMS/nginx-1.14.1-1.el7_4.ngx.src.rpm
rpm -ivh --prefix=/home/vagrant/ nginx-1.14.1-1.el7_4.ngx.src.rpm

sudo wget ftp://ftp.fi.muni.cz/pub/openssl/source/openssl-1.1.1f.tar.gz
sudo tar -xvf /home/vagrant/openssl-1.1.1f.tar.gz


sudo sudo yum-builddep /home/vagrant/rpmbuild/SPECS/nginx.spec
sudo rpmbuild -bb /home/vagrant/rpmbuild/SPECS/nginx.spec

sudo yum localinstall -y /home/vagrant/rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm
sudo systemctl start nginx

sudo mkdir /usr/share/nginx/html/repo
sudo cp /home/vagrant/rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm /usr/share/nginx/html/repo/
sudo wget http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm -O /usr/share/nginx/html/repo/percona-release-0.1-6.noarch.rpm

sudo createrepo /usr/share/nginx/html/repo/
