#!/bin/bash

sudo nginx -t
sudo nginx -s reload

curl -a http://localhost/repo/


cat >> /etc/yum.repos.d/otus.repo << EOF
[otus]
name=otus-linux
baseurl=http://localhost/repo
gpgcheck=0
enabled=1
EOF
yum repolist enabled | grep otus
sudo yum install percona-release -y
